---

name: add issue to projects

on: # yamllint disable-line rule:truthy
  issues:
    types:
      - reopened
      - opened

jobs:
  add-issue-to-test:
    permissions:
      repository-projects: write
    uses: kernelsam/shared-workflows/.github/workflows/add-to-project.yml@main
    with:
      project-number: "2"
      classic: false
    # secrets:
    #  ISSUE_PR_RW_TOKEN: ${{ secrets.ISSUE_PR_RW_TOKEN }}
