---

name: add issue to projects

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-issue-to-test:
      uses: kernelsam/shared-workflows/.github/workflows/add-to-project.yml@main
      with:
        project-number: "2"
      #secrets:
      #  ISSUE_PR_RW_TOKEN: ${{ secrets.ISSUE_PR_RW_TOKEN }}
