name: add issue to projects

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-issue-to-test:
    uses: kernelsam/shared-workflows/.github/workflows/add-to-project.yaml@main
    steps:
      - name: Add issue to test project
        with:
          project-number: "2"