---

name: add issue to projects

on: # yamllint disable-line rule:truthy
  issues:
    types:
      - reopened
      - opened

jobs:
  add-issue-to-test:
    uses: kernelsam/shared-workflows/.github/workflows/add-to-project.yml@main
    with:
      project-number: "2"
      classic: false
    secrets:
      PROJECT_RW_TOKEN: ${{ secrets.PROJECT_RW_TOKEN }}
