name: Dependabot approve and merge

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump steps Context
        env:
          STEPS_CONTEXT: ${{ toJSON(github) }}
        run: echo "$STEPS_CONTEXT"

  dependabot-approve-and-merge-patch:
    secrets:
      SENZING_GITHUB_CODEOWNER_PR_RW_TOKEN: ${{ secrets.CODEOWNER_PR_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/dependabot-approve-and-merge.yaml@119-skern
    with:
      update-type: "patch"

  dependabot-approve-and-merge-minor:
    secrets:
      SENZING_GITHUB_CODEOWNER_PR_RW_TOKEN: ${{ secrets.CODEOWNER_PR_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/dependabot-approve-and-merge.yaml@119-skern
    with:
      update-type: "minor"
