---

name: 'dependabot automation'

on:
  pull_request:
    branches: [main]

env:
  PR_OPENED: ${{ github.event.pull_request.opened }}
  PR_REOPENED: ${{ github.event.pull_request.reopened }}

jobs:

  add-pr-to-test:
      if: ${{ github.actor == 'dependabot[bot]' }} && ${{ env.PR_OPENED == true || env.PR_REOPENED == true }}
      uses: kernelsam/shared-workflows/.github/workflows/add-to-project.yml@main
      with:
        project-number: "2"

  dependabot-approve-and-merge:
      permissions:
        contents: write
        pull-requests: write
      uses: kernelsam/shared-workflows/.github/workflows/dependabot-automation.yml@main
      secrets:
        CODEOWNER_PR_APPROVAL_TOKEN: ${{ secrets.CODEOWNER_PR_APPROVAL_TOKEN }}
