name: 'dependabot automation'

on: [pull_request]

permissions:
  pull-requests: write

jobs:
  call-dependabot-automation:
    uses: kernelsam/shared-workflows/.github/workflows/dependabot-automation.yml@main
    with:
      enable-dependabot-automation: true
    secrets:
      CODEOWNER_PR_APPROVAL_TOKEN: ${{ secrets.CODEOWNER_PR_APPROVAL_TOKEN }}
