name: 'dependabot automation'

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  debug-test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug env vars
        run: if [ -z ${GH_TOKEN+x} ]; then echo "GH_TOKEN is unset"; else echo "GH_TOKEN is set to $GH_TOKEN"; fi
        env:
          GH_TOKEN: ${{ secrets.PR_APPROVAL_TOKEN }}
  shared:
    uses: kernelsam/shared-workflows/.github/workflows/dependabot-automation.yml@main
    with:
      enable-dependabot-automation: true
    secrets:
      PR_APPROVAL_TOKEN: ${{ secrets.PR_APPROVAL_TOKEN }}
