name: Receiver

on:
  repository_dispatch:
    types: [some_event]

concurrency:
  group: receiver
  cancel-in-progress: false

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "payload Foo '${{ github.event.client_payload.foo }}'"
          sleep 2m
