---

name: 'pr test'

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'

add-pr-to-test:
    if: ${{ ( github.event.action  == "opened" || github.event.action  == "reopened" ) }}
    uses: kernelsam/shared-workflows/.github/workflows/add-to-project.yml@main
    with:
      project-number: "2"
      classic: false
    secrets:
      ISSUE_PR_RW_TOKEN: ${{ secrets.ISSUE_PR_RW_TOKEN }}