name: win test

on:
  push:
    branches: [ "win-test" ]

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
        with:
          arch: x64
